name: Publish Binaries

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -c release --arch arm64 --arch x86_64
    - uses: actions/upload-artifact@v3
      with:
        name: dirsnapshot
        path: .build/apple/Products/Release/dirsnapshot
        
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dirsnapshot
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: dirsnapshot
