name: Publish Binaries

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -c release --arch arm64 --arch x86_64
    - name: github-action-publish-binaries
      uses: skx/github-action-publish-binaries@release-2.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: '.build/apple/Products/Release/dirsnapshot'

